parameters:
    algolia.indexer.class: Algolia\AlgoliaSearchSymfonyDoctrineBundle\Indexer\Indexer
    algolia.indexer_subscriber.class: Algolia\AlgoliaSearchSymfonyDoctrineBundle\EventListener\AlgoliaSearchDoctrineEventSubscriber
    algolia.document_indexer_subscriber.class: Algolia\AlgoliaSearchSymfonyDoctrineBundle\EventListener\AlgoliaSearchDoctrineDocumentEventSubscriber

services:
    algolia.indexer:
        class: %algolia.indexer.class%
        calls:
            - [setEnvironment, ["%kernel.environment%"]]
            - [setApiSettings, ["%algolia.application_id%", "%algolia.api_key%"]]
    algolia.indexer_subscriber:
        class: %algolia.indexer_subscriber.class%
        arguments: ["@algolia.indexer"]
        tags:
            - {name: doctrine.event_subscriber}
    algolia.document_indexer_subscriber:
        class: %algolia.document_indexer_subscriber.class%
        arguments: ["@algolia.indexer"]
        tags:
            - {name: doctrine_mongodb.odm.event_subscriber}
