parameters:
    algolia.indexer.class: Algolia\AlgoliaSearchBundle\Indexer\Indexer
    algolia.indexer_subscriber.class: Algolia\AlgoliaSearchBundle\EventListener\AlgoliaSearchEventSubscriber

services:
    algolia.indexer:
        class: %algolia.indexer.class%
        calls:
            - [setEnvironment, ["%kernel.environment%"]]
            - [setApiSettings, ["%algolia.application_id%", "%algolia.api_key%"]]
    algolia.indexer_subscriber:
        class: %algolia.indexer_subscriber.class%
        arguments: ["@algolia.indexer"]
        tags:
            - {name: doctrine.event_subscriber}
